### PR TITLE
changed chart date format

### PR DESCRIPTION
**Pull request by robalb**
as requested in #105 . The date format is now `28 jun` instead of `28/6`

### CODE REVIEW

**Comment by rickles42** [comment]
Testing the change locally on my machine now

**Comment by rickles42** [comment]
Looks good, the new dates are much easier for me to scan quickly 😁 I'll go ahead and merge your PR

**Comment by rickles42** [comment]
@robalb I noticed you made this commit to `robalb:master` and filed the PR from there. That makes it impossible to keep your fork synced with upstream while this PR is waiting to be merged. In general you should follow [GitHub flow](https://help.github.com/articles/github-flow/) and start with a topic branch, like `robalb:date-fix` that you branch off `robalb:master`.

**Comment by robalb** [comment]
Oh ok, I'll keep in mind that

**Pull request merged**
