### PR TITLE
Added firm tax section to investments + firm pages

### PR DESCRIPTION
**Pull request by keanucz**
This is a long-requested feature I hear, and so huzzah. I have delivered. I also linted the JavaScript files for presentation's sake. I'm struggling to test this as I get some sort of certificate error so if you could double-check it that'd be great

### CODE REVIEW

**Comment by thecsw** [comment]
+1,556 -1,546

Attach some pictures that this is working!

**Review by thecsw — CHANGES_REQUESTED** [review]
This PR includes linting and the new feature. If possible, can you please separate them? So we can actually see the code that is associated with the new feature, instead of linting everything

**Comment by keanucz** [comment]
I see your point. Good to see that you're back after 3 months :D

**Comment by thecsw** [comment]
This code is in the process of being discontinued. Because of that, they PR proposal is rejected. Thank you.

**Pull request closed without merging**
