### PR TITLE
Move template link to top of "INVEST" comment

### PR DESCRIPTION
**Pull request by lukenamop**
Created at the request of Noerdy, changes format of the "INVESTMENTS GO HERE" comment when a user links a template.

### CODE REVIEW

**Comment by Caribosaurus** [comment]
are you sure your commit is based on the latest comit?

**Comment by lukenamop** [comment]
@Caribosaurus yes, if you take a look at the "Files changed" tab you'll see that I only made changes in 11 lines of code.

**Comment by Caribosaurus** [comment]
Very true, It's weird the commit tab shows 10 commits

**Comment by lukenamop** [comment]
It's due to my own GitHub inadequacy, I wasn't able to successfully rebase my fork (or something, I'm not sure) so I just did some weird merge stuff. It's not pretty in terms of commits but it is correct.

**Review by thecsw — APPROVED** [review]
approved

**Comment by thecsw** [comment]
squashing this.

**Pull request merged**
