### PR TITLE
Modifying the return function

### PR DESCRIPTION
**Pull request by jimbobur**
**NOTE:** If you aren't happy with the new function behavior, let me know. I can fiddle around with the parameters to find ones that give a behaviour you like. It's quite tricky to strike a balance that's fair without being too easy.

Had a look at the upvote values for the top posts of all time in memeconomy. Played around with the function parameters to generate something more reasonable based on the sub's history and typical upvotes we might actually expect to see.

New function break even now at 74/75 upvotes, but you don't double your money til around 360 upvotes. After that it levels off and the triple-return point isn't til 905 upvotes. If you want to make 5 times your money back, the post would need to gain nearly 2900 upvotes.

If you invested in the highest-upvoted post of all time in the sub back when it was at 1 upvote, you'd get roughly 21x your money back. For the highest-upvoted post in reddit's history, it would be roughly x37.

Change in upvotes	Multiplier
0	0
2	0.203490649
5	0.304535595
10	0.413134306
50	0.838760676
100	1.137866363
200	1.543634431
500	2.310138729
1000	3.133944196
1020	3.16137005
1021	3.162733404
2000	4.251522259
5000	6.362650395
8000	7.824396558
10000	8.63159906
20000	11.70966464
50000	17.52419435
70000	20.32050032
80000	21.55017759  (Highest voted post of all time in memeeconomy)
100000	23.77339789
150000	28.41655413
200000	32.25109445
283000    37.57312269  (New upper cap in the code. Highest-voted post of all time on reddit)
300000	38.5500203
400000	43.7519743
500000	48.26563907
600000	52.29712437
750000	57.69234806 (Old upper cap in the code. Nothing in the history of reddit has even been this highly upvoted).

### CODE REVIEW

**Comment by jimbobur** [comment]
Ah damn, I forgot to update the readme in this pull request.

**Comment by jimbobur** [comment]
I forgot to update readme.

**Comment by jimbobur** [comment]
Readme and plot actually updated now.

**Comment by jimbobur** [comment]
That's weird. The diff isn't showing the new plot but it shows up in commit [2a6281f](https://github.com/thecsw/memeinvestor_bot/pull/29/commits/2a6281fd6c682b5bd4d0c3fdb5297ce5ef0c619d)
**EDIT**: Wait, my bad, I think it's fine.

**Comment by jimbobur** [comment]
Ok, I've modified the code/README again just now to also lower the multiplier cap to 283,000 upvotes, the highest upvoted post ever on reddit, as it seems a more sensible limit.

**Comment by thecsw** [comment]
Seems good, merging! Thanks!

**Comment by thecsw** [comment]
hey! can you add me on discord? I have something to talk to you about. thecsw#2451

**Comment by jimbobur** [comment]
@thecsw Hey yeah, I've been afk for a bit this weekend, sure, I've just sent a request on discord. I assume it's about the changes to the formula. I'm just reading it now, but it seems sensible. I'm gonna fiddle around with the formula later to see how it behaves.

**Pull request merged**
