### PR TITLE
Cleaned up the README a bit

### PR DESCRIPTION
**Pull request by rickles42**

### CODE REVIEW

**Comment by ometrist** [comment]
Can you fix the part of the README that says "dominate the market from **them** on" and replace it with "dominate the market from **then** on, in the paragraph about Step 1? 

Also the graph for step 1 needs the Y-axis changed to be "Initial Growth Factor" instead of what it currently is. I think the current y-axis label is something like "initial investment multiplier". 

I'll put a picture of a graph of x^1/3 that I like that you guys can use if you want, just seemed to make a little more sense to zoom in on the #'s that people can use to interpolate their own investments like 90% of the time 

[HERE IS THE GRAPH I WOULD LIKE YOU GUYS TO USE :)](https://imgur.com/j0U2Gzp)

**Comment by rickles42** [comment]
I addressed the typo pointed out by ometrist above, but I'll let @jimbobur decide about the graph suggestion. I recommend filing a new issue to track your chart request.

**Comment by ometrist** [comment]
I'm like Jon Snow when it comes to coding. You guys are the real MVP

**Comment by jimbobur** [comment]
Resolved merge conflict and changed section telling user how to invoke a command so that it now instructs users to reply to the bot's top-level comment or one of its subsequent replies. This should bring the readme instructions into line with the anti-spam measures we are intending to implement.

**Pull request merged**
