### PR TITLE
Limit posting

### PR DESCRIPTION
**Pull request by thecsw**
Okay, this is quite huge, lemme break it down.
Now, submitter is connected to the database because we filter all our new submissions. So. if you want to post a meme, you would need a minimum of 1000 MemeCoins to do that or 10%. If your balance is exactly 1000, the bot will take all of it. If you have 2000, it will take only 1000. But if your balance is greater than 10,000 you will start paying full 10% fee. If you have 999,999 MemeCoins, you will pay 99,999. This is the huge update. Docker dependency added successfully. Also, comments with balances are bold now. This needs a review.

Tests can be found on the [test subreddit](https://reddit.com/r/memeinvestor_test)

### CODE REVIEW

**Comment by thecsw** [comment]
Oof. This is asmost embarassing to say but I forgot that upstream remote on my laptop points to organization's repo and I nearly force pushed the update to the upstream master. Thank god git yelled at me and didn't let me do that. Kids, always `git remote show` your pointers!

**Comment by robalb** [comment]
Hey nice to see that the development is back on track! Btw, shouldn't this go on the season2 branch?

**Comment by thecsw** [comment]
This feature was requested by the subreddit's mod team. I can move it there or make a project that will have multiple branches!

**Comment by thecsw** [comment]
Merging this. Wish me luck!

**Comment by thecsw** [comment]
You are right, you will go broke after your first post. You can just get the bailout of 100 MemeCoins.

**BUT!**

Due to multiple commentns and arguments, I brought down the minimum tax from 1000 to 250.

**Pull request merged**
