### PR TITLE
Re-added safeguard on investment return multiplier calculation 

### PR DESCRIPTION
**Pull request by jimbobur**
Trying to calculate mult when du is negative will fail (fractional power of a -ve number isn't a real number). This ensures mutliplier calculation doesn't break if a post is downvoted from where it was at the time of investment.

### CODE REVIEW

**Comment by jimbobur** [comment]
I think I've messed something up here when I tried to update my fork to the SQL rewrite. I only changed a few lines of code.

**Comment by thecsw** [comment]
Hey! Can you update it? ```__main__``` got renamed to main and we have a merge conflict

**Comment by thecsw** [comment]
ah, just some timers got conflicted, I will get back to this after finishing the bot

**Comment by thecsw** [comment]
However, I don't understand the conflict on Line 202

**Comment by thecsw** [comment]
Hey, thanks! I added the fix to the main file. Thanks! You can check the change in the latest SQL_rewrite commit above!

**Comment by jimbobur** [comment]
Thanks, I'm not much of an expert on GitHub and I couldn't figure out why there was a merge conflict.

**Pull request closed without merging**
