### PR TITLE
Automatically set up the database on first run if it's missing. Fixes #73

### LINKED ISSUE #73: Deploying the bot should create an empty database if no database exists
The code today depends on the existence of a pre-initialized database, which makes it difficult to do your own test deployment from scratch.

If someone who understands SQLAlchemy could update the project to handle the case when no Investor or Investment tables exist (at least when DRY_RUN is enabled), that would be super helpful.

### PR DESCRIPTION
**Pull request by rickles42**
This change addresses Issue #73 by using SQLAlchemy to spin up a new database and create empty Investors and Investments tables (if they do not exist). This makes it much easier for a new contributor to get up and running with a local copy of the bot.

Summary of changes:

- Refactored the `models` folder. Combining Investors.py and Investments.py allows us to import the `Base` object into main.py, where it can be used to call `Base.metadata.create_all()` which initializes the tables if needed.

- Changed `func.utcnow()` to `func.current_timestamp()` in the Investments table definition. Looks like `utcnow()` is incompatible with MySQL - it gave an error if I tried to create a table automatically, or even manually, using that function. My research suggests `current_timestamp()` should work the same way, but I'm definitely no expert. This change could have introduced a timezone bug. **Edit:** Actually this works pretty differently, so I've updated with a custom function to get the `unix_timestamp()` behavior originally desired.

- Added a handful of logging directives to main.py.

- Updated the README. We're still not at one-touch deployment of a local bot, but we're getting closer.

### CODE REVIEW

**Comment by thecsw** [comment]
Nice! I love the more active logging and code refactoring. I will wait for @dzervas. Thanks!
#73 has been reviewed by @dzervas

**Comment by rickles42** [comment]
(Rebased this branch onto latest master for easier review)

**Comment by thecsw** [comment]
We have a merge conflict!

**Comment by rickles42** [comment]
I will rebase this onto the latest master and resolve the merge conflicts. Then you can take a look and merge

**Comment by rickles42** [comment]
Okay @thecsw Try having a look at the code now and merging if you approve

**Comment by thecsw** [comment]
Please consult @dzervas on this request

**Comment by thecsw** [comment]
This one fixes #73

**Pull request merged**
