### PR TITLE
Modified win/lose behaviour

### PR DESCRIPTION
**Pull request by jimbobur**
**EDIT**: Ignore this comment, see later comments below

A return multiplier of less than 1 is failure (get back less memecoins than you invested)
A return multiplier of exactly 1 is break-even (get back the same amount of memecoins as you invested)
A return multiplier of greater than 1 is success (get back more memecoins than you invested).

### CODE REVIEW

**Comment by thecsw** [comment]
We wanted to do so that if the post gained less than 30% of initial upvotes, investment is lost. We should have winners and losers

**Comment by jimbobur** [comment]
@thecsw Ah I see, I was thinking of it in terms of relative growth, but posts usually only ever grow or stay where they are, so this makes sense if we want winners/losers.
We could keep the break even but it's not really necessary as the win-lose cutoff is arbitrary anyway.

However, if they lose, shouldn't they get back zero of what they invested, or some sub-multiple? As far as I can make out from the code, currently they get back **amount * factor** whether they win or lose. I'm going to have a quick look at this now.

**Comment by thecsw** [comment]
Maybe if they have less than 30% growth, return only their percent of growth by investment amount?

Return = (new/old - 1) * investment.amount?

**Comment by jimbobur** [comment]
That should not have deleted the png. hang on..

**Comment by jimbobur** [comment]
Basically now if they lose they get back the amount they invested multiplied by the difference between the win/lose threshold and their multiplier. So, for e.g. if they invest 100 coins but their multiplier is only 1.1, they'll get back (1.3 - 1.1) * 100 = 20 memecoins, i.e. they lose 80 memecoins.

**Comment by jimbobur** [comment]
Oop, I think my text editor indentation is set up differently. Will fix.

**Comment by jimbobur** [comment]
I've just realised I've got this totally backwards. Will change now.

**Comment by jimbobur** [comment]
Ok, so now there's 3 distinct zones:  
- **factor > win_threshold (win):** 
  return = investment * factor
- **1 < factor < win_threshold (lose, some money back):** 
  return = investment * (factor - 1) / (win_threshold - 1) 
- **factor < 1 (lose investment):** 
  return = 0

EXAMPLES:  
- **[WIN]** invest 100, factor  = 1.4 --> return = 100 * 1.4 = 140 MC
- **[LOSE]** invest 100, factor = 1.1 -- > return = 100*( 1.1 -1 )/(1.3 - 1) = 100*(0.1/0.3) = ~33 MC
- **[TOTALLY LOSE (post not upvoted)]** invest 100, factor = 1 --> return = 0 MC
- **[TOTALLY LOSE (post downvoted)]** invest 100, factor = 0.8 --> return = 0 MC

PLOT:  
image

**Comment by jimbobur** [comment]
I'm wondering now if it might be better to fold this block of if-elif-else decision making into the calculate function. That way check investments can just report a success/failure based on if the return multiplier is less than one or not.

**Comment by dzervas** [comment]
Ok, the main problem is:
I invest 100 on 2 upvotes. There's no way I won't get more than 200. Every post will AT LEAST get to 10 upvotes.

**Comment by jimbobur** [comment]
Bear in mind the factor is the cube root of the change in upvotes, so if:
starting upvotes = 2
finishing upvotes  = 10
**then:**
factor = CUBEROOT(10/2)= 1.709976
**so:** factor > 1.3,
**thus:**
return = factor * investment = **~171 MC** 

That said, your point still stands that a low-upvote post that only goes to, say, 10 upvotes will still gain a fair amount of memecoins, despite taking the cube root of the proportional change in upvotes.

**Comment by dzervas** [comment]
That’s still too much. We want very early people get at most 100x on REALLY successful memes

so get 10k when invested 100 at 2 ups and new ups is 60k

**Comment by dzervas** [comment]
Oh, it’s actually not.
Yea sounds real nice.
On 40k in 4 hours you get 27k. pretty decent
We could even lower the minimum factor a bit (maybe 1.2?)

**Comment by jimbobur** [comment]
### EDIT:I've further condensed this wall of info into a summary for a range of factor thresholds; see next comment below.

I've done some example calculations for 1.3 and 1.2 minimum factor. I've omitted the intermediate calculation columns because otherwise it's just a wall of numbers, but I can re-add them if you want all the gory details:


**Factor Threshold: 1.3** 

INVESTMENT   / MemeCoins | Starting upvotes | Ending Upvotes | WIN/LOSE/NOTHING | INVESTMENT **RETURN / MemeCoins**
-- | -- | -- | -- | --
100 | 2 | 2 | NOTHING | **0**
100 | 2 | 10 | WIN | **171**
100 | 2 | 100 | WIN | **368**
100 | 2 | 1000 | WIN | **794**
100 | 2 | 10000 | WIN | **1710**
100 | 100 | 100 | NOTHING | **0**
100 | 100 | 1000 | WIN | **215**
100 | 100 | 10000 | WIN | **464**
100 | 1000 | 1000 | NOTHING | **0**
100 | 1000 | 2000 | LOSE | **87**
100 | 1000 | 3000 | WIN | **144**
100 | 1000 | 5000 | WIN | **171**
100 | 1000 | 10000 | WIN | **215**
100 | 10000 | 15000 | LOSE | **48**

**Factor Threshold: 1.2**

INVESTMENT   / MemeCoins | Starting upvotes | Ending Upvotes | WIN/LOSE/NOTHING | **INVESTMENT RETURN / MemeCoins**
-- | -- | -- | -- | --
100 | 2 | 2 | NOTHING | **0**
100 | 2 | 10 | WIN | **171**
100 | 2 | 100 | WIN | **368**
100 | 2 | 1000 | WIN | **794**
100 | 2 | 10000 | WIN | **1710**
100 | 100 | 100 | NOTHING | **0**
100 | 100 | 1000 | WIN | **215**
100 | 100 | 10000 | WIN | **464**
100 | 1000 | 1000 | NOTHING | **0**
100 | 1000 | 2000 | WIN | **126**
100 | 1000 | 3000 | WIN | **144**
100 | 1000 | 5000 | WIN | **171**
100 | 1000 | 10000 | WIN | **215**
100 | 10000 | 15000 | LOSE | **72**

 **SUMMARY** 
values that change have been **highlighted**.
Investment = 100 MemeCoins

Starting upvotes | Ending Upvotes | RETURN (**thresh = 1.3**) / MemeCoins | RETURN (**thresh = 1.2**)   / MemeCoins
-- | -- | -- | --
2 | 2 | 0 | 0
2 | 10 | 171 | 171
2 | 100 | 368 | 368
2 | 1000 | 794 | 794
2 | 10000 | 1710 | 1710
100 | 100 | 0 | 0
100 | 1000 | 215 | 215
100 | 10000 | 464 | 464
1000 | 1000 | 0 | 0
**1000** | **2000** | **87** | **126**
1000 | 3000 | 144 | 144
1000 | 5000 | 171 | 171
1000 | 10000 | 215 | 215
**10000**| **15000** | **48** | **72**

**Comment by jimbobur** [comment]
**Extending this to more threshold values:**
Colour code:
- GREEN: WIN
- YELLOW: LOSE
- RED: NOTHING 

image

**Comment by jimbobur** [comment]
Moved factor thresholding code to **calculate** function; now all **check_investments** has to know/care about is whether you got back more memecoins than you invested or not.

**Comment by dzervas** [comment]
Wow, you’re good with numbers. And visualization.
I think I like the 1.2 better. It just feels right

**Comment by jimbobur** [comment]
If 1.2 is the consensus, I'll change the threshold to that

**Comment by thecsw** [comment]
Okay! Will be waiting for fixes and then will merge.

**Comment by jimbobur** [comment]
I'm also going to change the readme to reflect these new changes.

**Comment by jimbobur** [comment]
Ok, the readme should be good, and notwithstanding any bugs, this PR should be ready.

**Pull request merged**
