### PR TITLE
Add graph of investment return multiplier 

### PR DESCRIPTION
**Pull request by jimbobur**
Handy graph for information purposes. Is there a way to embed or link to this in the README?

### CODE REVIEW

**Comment by thecsw** [comment]
uhm? This is just all commits together. However, I will add the image!

**Comment by jimbobur** [comment]
@thecsw Oh, does it? Sorry about that! I just wanted to add that one png file. I'm really a novice when it comes to using github; I haven't used it much before.

**Comment by thecsw** [comment]
Are you using git?

**Comment by jimbobur** [comment]
Iv'e just been doing everything via the github website. I'm usually on several different machines at different points in the day, but I'm gonna put it on my home machine when I get a moment.

**Pull request closed without merging**
