### PR TITLE
Show user balance in 'you don't have enough Mc' bot response

### LINKED ISSUE #209: Show user balance in 'you don't have enough Mc' bot response
As suggested [here](https://www.reddit.com/r/MemeInvestor_bot/comments/91ryrs/suggestion_read_the_post_i_suck_at_coming_up_with/?utm_source=reddit-android), the bot response should include the current user balance

### PR DESCRIPTION
**Pull request by thecsw**
Fixes #209

### CODE REVIEW

**Review by rickles42 — CHANGES_REQUESTED** [review]
Instead of telling people the number of MemeCoins they lack, it would be more useful if we did the simpler thing and told them how many they have. Most of the time the user is trying to invest, so knowing how much they have left lets them just copy-paste that value into a new `!invest` command and not have to do any mental math.

**Comment by thecsw** [comment]
OKay, will update it

**Comment by thecsw** [comment]
Okay, I updated it!

**Review by thecsw — COMMENTED** [review]
I made some changes as requested!

**Review by rickles42 — APPROVED** [review]

**Comment by rickles42** [comment]
Tested locally, works fine.

**Comment by rickles42** [comment]
Deployed

**Pull request merged**
