### PR TITLE
Firm invite issues test

### PR DESCRIPTION
**Pull request by lukenamop**
Added a test to firms.py

### CODE REVIEW

**Comment by thecsw** [comment]
For some reason there is a conflict in the PR. I like the test you're adding. I am not sure what causes the issues with inability to join The Iron Bank

**Comment by lukenamop** [comment]
Yeah I don't know what the conflict is. The test I added fails though, it needs to be solved.

**Comment by lukenamop** [comment]
Just kidding, figured it out and fixed it.

**Comment by lukenamop** [comment]
(Test still fails)

**Comment by thecsw** [comment]
Interesting... I will take a look soon

**Comment by keanucz** [comment]
*takes a look a month and 2 weeks later*

**Comment by thecsw** [comment]
I would think that #403 fixes the issue.

**Pull request closed without merging**
