### PR TITLE
Improve backups

### PR DESCRIPTION
**Pull request by thecsw**
Hey! A little update. Please make a squash merge! Thanks!

### CODE REVIEW

**Comment by rickles42** [comment]
Did you try this locally? It doesn't seem like it would work. Looks like it first saves the backup to `/tmp/backup...` and then tries to copy it from `/tmp//tmp/backup...`

Also, what is the purpose of the empty `example.sql` file?

**Comment by thecsw** [comment]
On the server check our `backup.sh` file and execute it with `./backup.sh`. You would see that it's working normally.

Empty file is needed to add backups folder

**Comment by rickles42** [comment]
> On the server check our `backup.sh` file and execute it with `./backup.sh`. You would see that it's working normally.

I see that the script on the server works, but it's not the same as the script in your PR, which doesn't work. Notice the path differences I mentioned above. It's also fine for us to hardcode the database name and user into the backup script---it's hardcoded everywhere else, and the container name is hardcoded as well, so we shouldn't bother trying to make this script portable. So you can change `DATABASE_NAME` and `USERNAME`.

> Empty file is needed to add backups folder

Let's remove the empty file and just add a `mkdir` to the script. That way we don't add a weird extra folder and empty file to every clone of the repo, when most people aren't ever going to run the backup script locally (it's mostly just for us).

**Comment by thecsw** [comment]
Oh, so you want to hardcode the production database creds from `.env`? Okay. I just thought to keep the creds in secret and only then realized that we have them written in `.env.example`. Haha

**Comment by rickles42** [comment]
Well I'd rather leave the password out of this file and just have the user type it. But the host name of the database is totally fine to hardcode, I mean it's already hardcoded elsewhere in this script.

Probably a good idea to remove the password from  `.env.example`. Our db isn't exposed to the public but making people choose their own when they clone the project is probably a smart idea.

**Comment by thecsw** [comment]
True

**Comment by rickles42** [comment]
Looks good

**Pull request merged**
