### PR TITLE
Added Rank attribute to Website

### PR DESCRIPTION
**Pull request by jacob-padley**
I've added a "rank" feature to the website which allows you to view your overall investor rank based on Net Worth on the meme.market website. This allows users outside of the top 50 to view their ranks.

[Evidence of no errors](https://imgur.com/jXg8UCi)
[Evidence that feature works on my test server](https://imgur.com/a6xvbow)

### CODE REVIEW

**Comment by thecsw** [comment]
Hey! I just want to confirm I got your PR. I will test it today

**Comment by thecsw** [comment]
Hey! I looked at your PR and it look solid. Quick question before approving, are ranks ordered in a descending order? Secondly, can you just briefly describe here how you determine someone's rank. Thanks

**Comment by jacob-padley** [comment]
Ranks are ordered in descending order, determined by their net worth just like the leaderboard. It's like a way to see your place on the leaderboard even if you're not in the top 50 investors (what is shown on the website)

**Comment by thecsw** [comment]
Alright, I like! It is good to see your overall rank. I pulled your branch and it seems to be working fine! 

The only possible issue I see is the performance. As we have to calculate Networths and that is an expensive operation. However, in my new DB proposal, networth will be a separate column, so it should be easier to get info.

There is always this sacrifice of time and space complexity.

**Comment by thecsw** [comment]
Hey! I deployed the update and it is live. However, the website does not show the ronk. I tried to manually clear cache and force refresh, it did not work. Please feel free to inspect the issue. If it comes from my side, I will be happy to help. Here is what I get:

```
u/thecsw
net worth: 11,000 M¢
balance: 11,000 M¢
rank: ---
gone broke: 0 times
completed investments: 0
firm: 
```

Instead of `rank:63271`

**Pull request merged**
