### PR TITLE
Made an update so any number of spaces between !invest and an amount …

### PR DESCRIPTION
**Pull request by thecsw**
…can be accepted.

[Testing](https://www.reddit.com/r/memeinvestor_test/comments/93bo89/new_regex/)

### CODE REVIEW

**Comment by thecsw** [comment]
Don't merge yet

**Comment by rickles42** [comment]
It sounds like you may already be making some changes but for clarity let's use `\s+` instead of `\s*` since this doesn't work with zero spaces anyway. (Another part of the command parsing code assumes a space)

**Comment by thecsw** [comment]
Alright

**Comment by thecsw** [comment]
This was the first time I used the GitHub code editor. Feels dirty

**Pull request merged**
