### PR TITLE
Revamp investment formula and add visualizer

### PR DESCRIPTION
**Pull request by rickles42**
Lots of work went into the formula rewrite, mainly from jimbobur and
rickles42.

### CODE REVIEW

**Comment by rickles42** [comment]
@jimbobur will want to take a quick look over this. It's basically the same as the last version I posted to the #formula channel

**Review by jimbobur — COMMENTED** [review]
Have pulled this latest version, looked over it and done a quick test run of the formula visualiser. Everything looks good.

**Comment by jimbobur** [comment]
@rickles42 these parameters seemed to differ from the ones in the last commit I pulled; did you tweak them again?

**Comment by rickles42** [comment]
@jimbobur Yes, just a small tweak in the low end.

**Pull request merged**
