### PR TITLE
Added command line tool to perform test calculations with the formula.

### PR DESCRIPTION
**Pull request by jimbobur**
After @thecsw asking about double checking the formula. I figured I'd add a quick tool that allows you to perform test investment calculations from the command line.

### CODE REVIEW

**Comment by rickles42** [comment]
@jimbobur This code is pretty isolated from the rest of the project so feel free to merge this PR whenever you're happy with it. If you have a lot of work-in-progress commits to the PR branch, like those "Trivial tweaks" above, you can use the Squash Merge option (click the arrow on the green merge button) instead of the default "Create a merge commit" option to clean them up.

**Comment by jimbobur** [comment]
Added meme performance plot drawing to tool. Now plots a graph with the return curve and your meme's performance on it.

**Comment by rickles42** [comment]
Hey @jimbobur assuming you got the graphics to work, would it be possible to use `plt.show()` instead of saving the figure as an image to disk? For an interactive tool like this (where I'm likely to execute it, look at it, execute it, look at it and I explore) I think it would be nicer to just have the graph appear.

**Comment by jimbobur** [comment]
@rickles42 can do. Still couldn't get show() to work on my setup :(
I'll add it and put the file save as an option.

**Comment by rickles42** [comment]
@jimbobur The window doesn't show up for me. I think it needs to use `plt.show()` instead of `fig.show()` - that makes it work. I can push that fix.

**Comment by jimbobur** [comment]
@rickles42 Ah ok, I can't test the show() function on my end; feel free to push that fix if it works.

**Pull request merged**
