### PR TITLE
Expand firms

### PR DESCRIPTION
**Pull request by thecsw**
This is more of a suggestion on Firms table expansion. To finish, more code and methods should be added. This PR should be based on #290

### CODE REVIEW

**Review by mappum — CHANGES_REQUESTED** [review]
Pretty good, interesting to use the firm.members field (hopefully we don't forget to modify this in the future if there is ever some edge case that adds or removes a member, although I don't think there is currently). The alternative would be a count query, although I'm sure your way is more performant.

I believe there should also be a count for number of executives since there will be a separate cap for that as well.

**Comment by thecsw** [comment]
firm.size -> shows the size of the firm (all members)
firm.execs -> number of executives in the firm (CEO not included)
firm.boost -> the profit boost that firm members git from their investments (1 is 0%, 1.1 is 10%), meant to be an upgrade
firm.tax -> the tax that all members of a firm should pay from their profits, needs to be regulated and limited, not 0% and not 100%, add validation steps in the code!
firm.rank -> firm's rank and the upgrade step, 1st lvl, 2nd lvl, and etc.

**Comment by mappum** [comment]
Just to clarify, are the fields `boost`, `tax`, and `rank` not going to be used in this update but are being created for later?

**Comment by thecsw** [comment]
I think we can implement an `!upgrade` command that will upgrade the firm's profit `boost`, `rank`. And `!tax amount` to change firm's tax withholding. (rn it is hardcoded to be 15%)

**Pull request merged**
