### PR TITLE
Added more links.

### PR DESCRIPTION
**Pull request by thecsw**

### CODE REVIEW

**Comment by rickles42** [comment]
I will take a look this evening and make some edits.

I'm a little bit worried that tripling the number of hyperlinks (doubling the number of external hyperlinks) could put the bot at risk of getting banned again. I'd rather err on the side of caution. I'll think about a way to phrase stuff that works okay without another hyperlink.

(I think linking to another subreddit is probably fine tho)

**Comment by rickles42** [comment]
@thecsw I've pushed a revision, and I kept all the links. Let me know if this looks good and I'll merge it.

**Review by rickles42 — APPROVED** [review]

**Comment by rickles42** [comment]
Link to example of what it looks like:

https://www.reddit.com/r/memeinvestor_test/comments/90rg9r/torino/e2zn54i

**Comment by robalb** [comment]
Maybe we can remove the github link. We already have the github logo in the navbar on the website, and we can add another link to it on the sidebar in the new subreddit or as a sticky post

**Comment by rickles42** [comment]
Yeah I think I agree that we could do without the GitHub link.

**Pull request merged**
